/** Known PC games — developer, publisher, year, genre. */
export interface KnownGameEntry {
  developer: string;
  publisher?: string;
  year?: number;
  genre?: string;
  sizeHint?: string;
}

export const KNOWN_GAMES: Record<string, KnownGameEntry> = {
  "grand theft auto": { developer: "Rockstar North", publisher: "Rockstar Games", year: 2013, genre: "Action", sizeHint: "95 GB" },
  "gta": { developer: "Rockstar North", publisher: "Rockstar Games", year: 2013, genre: "Action", sizeHint: "95 GB" },
  "call of duty": { developer: "Infinity Ward", publisher: "Activision", year: 2023, genre: "Action", sizeHint: "85 GB" },
  "need for speed": { developer: "Criterion Games", publisher: "Electronic Arts", year: 2022, genre: "Racing", sizeHint: "30 GB" },
  "forza horizon": { developer: "Playground Games", publisher: "Xbox Game Studios", year: 2023, genre: "Racing", sizeHint: "130 GB" },
  "forza": { developer: "Turn 10 Studios", publisher: "Xbox Game Studios", year: 2023, genre: "Racing", sizeHint: "100 GB" },
  "fifa": { developer: "EA Vancouver", publisher: "EA Sports", year: 2023, genre: "Sports", sizeHint: "50 GB" },
  "ea fc": { developer: "EA Vancouver", publisher: "EA Sports", year: 2024, genre: "Sports", sizeHint: "50 GB" },
  "assassin's creed": { developer: "Ubisoft Montreal", publisher: "Ubisoft", year: 2023, genre: "Action", sizeHint: "70 GB" },
  "far cry": { developer: "Ubisoft Montreal", publisher: "Ubisoft", year: 2023, genre: "Action", sizeHint: "60 GB" },
  "watch dogs": { developer: "Ubisoft Montreal", publisher: "Ubisoft", year: 2020, genre: "Action", sizeHint: "45 GB" },
  "cyberpunk": { developer: "CD Projekt Red", publisher: "CD Projekt", year: 2020, genre: "RPG", sizeHint: "70 GB" },
  "witcher": { developer: "CD Projekt Red", publisher: "CD Projekt", year: 2015, genre: "RPG", sizeHint: "50 GB" },
  "elden ring": { developer: "FromSoftware", publisher: "Bandai Namco", year: 2022, genre: "RPG", sizeHint: "60 GB" },
  "dark souls": { developer: "FromSoftware", publisher: "Bandai Namco", year: 2018, genre: "RPG", sizeHint: "25 GB" },
  "sekiro": { developer: "FromSoftware", publisher: "Activision", year: 2019, genre: "Action", sizeHint: "25 GB" },
  "god of war": { developer: "Santa Monica Studio", publisher: "Sony Interactive", year: 2022, genre: "Action", sizeHint: "70 GB" },
  "horizon": { developer: "Guerrilla Games", publisher: "Sony Interactive", year: 2022, genre: "Action", sizeHint: "100 GB" },
  "spider-man": { developer: "Insomniac Games", publisher: "Sony Interactive", year: 2022, genre: "Action", sizeHint: "75 GB" },
  "minecraft": { developer: "Mojang Studios", publisher: "Microsoft", year: 2011, genre: "Survival", sizeHint: "1 GB" },
  "red dead": { developer: "Rockstar Games", publisher: "Rockstar Games", year: 2019, genre: "Action", sizeHint: "150 GB" },
  "battlefield": { developer: "DICE", publisher: "Electronic Arts", year: 2023, genre: "Action", sizeHint: "100 GB" },
  "halo": { developer: "343 Industries", publisher: "Xbox Game Studios", year: 2021, genre: "Action", sizeHint: "75 GB" },
  "doom": { developer: "id Software", publisher: "Bethesda", year: 2020, genre: "Action", sizeHint: "80 GB" },
  "fallout": { developer: "Bethesda Game Studios", publisher: "Bethesda", year: 2015, genre: "RPG", sizeHint: "30 GB" },
  "skyrim": { developer: "Bethesda Game Studios", publisher: "Bethesda", year: 2011, genre: "RPG", sizeHint: "12 GB" },
  "resident evil": { developer: "Capcom", publisher: "Capcom", year: 2023, genre: "Horror", sizeHint: "50 GB" },
  "devil may cry": { developer: "Capcom", publisher: "Capcom", year: 2019, genre: "Action", sizeHint: "35 GB" },
  "monster hunter": { developer: "Capcom", publisher: "Capcom", year: 2022, genre: "Action", sizeHint: "80 GB" },
  "final fantasy": { developer: "Square Enix", publisher: "Square Enix", year: 2023, genre: "RPG", sizeHint: "100 GB" },
  "kingdom hearts": { developer: "Square Enix", publisher: "Square Enix", year: 2020, genre: "RPG", sizeHint: "50 GB" },
  "metal gear": { developer: "Kojima Productions", publisher: "Konami", year: 2015, genre: "Action", sizeHint: "28 GB" },
  "death stranding": { developer: "Kojima Productions", publisher: "505 Games", year: 2020, genre: "Adventure", sizeHint: "80 GB" },
  "ghost of tsushima": { developer: "Sucker Punch", publisher: "Sony Interactive", year: 2024, genre: "Action", sizeHint: "60 GB" },
  "uncharted": { developer: "Naughty Dog", publisher: "Sony Interactive", year: 2022, genre: "Adventure", sizeHint: "126 GB" },
  "last of us": { developer: "Naughty Dog", publisher: "Sony Interactive", year: 2023, genre: "Action", sizeHint: "100 GB" },
  "days gone": { developer: "Bend Studio", publisher: "Sony Interactive", year: 2022, genre: "Action", sizeHint: "70 GB" },
  "hitman": { developer: "IO Interactive", publisher: "IO Interactive", year: 2023, genre: "Action", sizeHint: "80 GB" },
  "tomb raider": { developer: "Crystal Dynamics", publisher: "Square Enix", year: 2018, genre: "Adventure", sizeHint: "40 GB" },
  "metro": { developer: "4A Games", publisher: "Deep Silver", year: 2019, genre: "Action", sizeHint: "80 GB" },
  "stalker": { developer: "GSC Game World", publisher: "GSC Game World", year: 2024, genre: "Survival", sizeHint: "150 GB" },
  "civilization": { developer: "Firaxis Games", publisher: "2K Games", year: 2024, genre: "Strategy", sizeHint: "20 GB" },
  "total war": { developer: "Creative Assembly", publisher: "Sega", year: 2023, genre: "Strategy", sizeHint: "60 GB" },
  "sims": { developer: "Maxis", publisher: "Electronic Arts", year: 2024, genre: "Simulation", sizeHint: "50 GB" },
  "planet coaster": { developer: "Frontier Developments", publisher: "Frontier", year: 2023, genre: "Simulation", sizeHint: "25 GB" },
  "euro truck": { developer: "SCS Software", publisher: "SCS Software", year: 2023, genre: "Simulation", sizeHint: "20 GB" },
  "flight simulator": { developer: "Asobo Studio", publisher: "Xbox Game Studios", year: 2024, genre: "Simulation", sizeHint: "150 GB" },
  "pes": { developer: "Konami", publisher: "Konami", year: 2021, genre: "Sports", sizeHint: "40 GB" },
  "nba 2k": { developer: "Visual Concepts", publisher: "2K Sports", year: 2024, genre: "Sports", sizeHint: "150 GB" },
  "wwe": { developer: "Visual Concepts", publisher: "2K Sports", year: 2024, genre: "Sports", sizeHint: "80 GB" },
  "mortal kombat": { developer: "NetherRealm Studios", publisher: "Warner Bros", year: 2023, genre: "Fighting", sizeHint: "100 GB" },
  "street fighter": { developer: "Capcom", publisher: "Capcom", year: 2023, genre: "Fighting", sizeHint: "60 GB" },
  "tekken": { developer: "Bandai Namco", publisher: "Bandai Namco", year: 2024, genre: "Fighting", sizeHint: "80 GB" },
  "pubg": { developer: "PUBG Studios", publisher: "Krafton", year: 2022, genre: "Action", sizeHint: "40 GB" },
  "fortnite": { developer: "Epic Games", publisher: "Epic Games", year: 2024, genre: "Action", sizeHint: "90 GB" },
  "apex legends": { developer: "Respawn Entertainment", publisher: "Electronic Arts", year: 2024, genre: "Action", sizeHint: "75 GB" },
  "valorant": { developer: "Riot Games", publisher: "Riot Games", year: 2020, genre: "Action", sizeHint: "25 GB" },
  "counter-strike": { developer: "Valve", publisher: "Valve", year: 2012, genre: "Action", sizeHint: "35 GB" },
  "cs2": { developer: "Valve", publisher: "Valve", year: 2023, genre: "Action", sizeHint: "35 GB" },
  "dota": { developer: "Valve", publisher: "Valve", year: 2013, genre: "Action", sizeHint: "15 GB" },
  "half-life": { developer: "Valve", publisher: "Valve", year: 2020, genre: "Action", sizeHint: "48 GB" },
  "portal": { developer: "Valve", publisher: "Valve", year: 2011, genre: "Adventure", sizeHint: "8 GB" },
  "left 4 dead": { developer: "Valve", publisher: "Valve", year: 2009, genre: "Action", sizeHint: "10 GB" },
  "borderlands": { developer: "Gearbox Software", publisher: "2K Games", year: 2024, genre: "Action", sizeHint: "100 GB" },
  "bioshock": { developer: "Irrational Games", publisher: "2K Games", year: 2016, genre: "Action", sizeHint: "25 GB" },
  "dishonored": { developer: "Arkane Studios", publisher: "Bethesda", year: 2017, genre: "Action", sizeHint: "30 GB" },
  "prey": { developer: "Arkane Studios", publisher: "Bethesda", year: 2017, genre: "Action", sizeHint: "42 GB" },
  "dead space": { developer: "Motive Studio", publisher: "Electronic Arts", year: 2023, genre: "Horror", sizeHint: "50 GB" },
  "alan wake": { developer: "Remedy Entertainment", publisher: "Epic Games", year: 2023, genre: "Horror", sizeHint: "90 GB" },
  "control": { developer: "Remedy Entertainment", publisher: "505 Games", year: 2020, genre: "Action", sizeHint: "42 GB" },
  "mass effect": { developer: "BioWare", publisher: "Electronic Arts", year: 2021, genre: "RPG", sizeHint: "120 GB" },
  "dragon age": { developer: "BioWare", publisher: "Electronic Arts", year: 2024, genre: "RPG", sizeHint: "100 GB" },
  "starfield": { developer: "Bethesda Game Studios", publisher: "Bethesda", year: 2023, genre: "RPG", sizeHint: "140 GB" },
  "baldur's gate": { developer: "Larian Studios", publisher: "Larian Studios", year: 2023, genre: "RPG", sizeHint: "150 GB" },
  "divinity": { developer: "Larian Studios", publisher: "Larian Studios", year: 2017, genre: "RPG", sizeHint: "60 GB" },
  "pillars of eternity": { developer: "Obsidian Entertainment", publisher: "Paradox", year: 2018, genre: "RPG", sizeHint: "20 GB" },
  "outer worlds": { developer: "Obsidian Entertainment", publisher: "Private Division", year: 2022, genre: "RPG", sizeHint: "50 GB" },
  "fall guys": { developer: "Mediatonic", publisher: "Epic Games", year: 2022, genre: "Action", sizeHint: "2 GB" },
  "among us": { developer: "Innersloth", publisher: "Innersloth", year: 2018, genre: "Adventure", sizeHint: "1 GB" },
  "hollow knight": { developer: "Team Cherry", publisher: "Team Cherry", year: 2017, genre: "Adventure", sizeHint: "9 GB" },
  "hades": { developer: "Supergiant Games", publisher: "Supergiant Games", year: 2020, genre: "Action", sizeHint: "15 GB" },
  "celeste": { developer: "Maddy Makes Games", publisher: "Maddy Makes Games", year: 2018, genre: "Adventure", sizeHint: "1 GB" },
  "stardew valley": { developer: "ConcernedApe", publisher: "ConcernedApe", year: 2016, genre: "Simulation", sizeHint: "500 MB" },
  "terraria": { developer: "Re-Logic", publisher: "Re-Logic", year: 2011, genre: "Adventure", sizeHint: "1 GB" },
  "rust": { developer: "Facepunch Studios", publisher: "Facepunch", year: 2024, genre: "Survival", sizeHint: "25 GB" },
  "ark": { developer: "Studio Wildcard", publisher: "Studio Wildcard", year: 2024, genre: "Survival", sizeHint: "100 GB" },
  "dayz": { developer: "Bohemia Interactive", publisher: "Bohemia", year: 2018, genre: "Survival", sizeHint: "20 GB" },
  "sons of the forest": { developer: "Endnight Games", publisher: "Endnight Games", year: 2024, genre: "Survival", sizeHint: "20 GB" },
  "forest": { developer: "Endnight Games", publisher: "Endnight Games", year: 2018, genre: "Survival", sizeHint: "5 GB" },
  "subnautica": { developer: "Unknown Worlds", publisher: "Unknown Worlds", year: 2018, genre: "Survival", sizeHint: "20 GB" },
  "no man's sky": { developer: "Hello Games", publisher: "Hello Games", year: 2024, genre: "Adventure", sizeHint: "15 GB" },
  "palworld": { developer: "Pocketpair", publisher: "Pocketpair", year: 2024, genre: "Survival", sizeHint: "40 GB" },
  "lies of p": { developer: "Neowiz Games", publisher: "Neowiz", year: 2023, genre: "Action", sizeHint: "50 GB" },
  "armored core": { developer: "FromSoftware", publisher: "Bandai Namco", year: 2023, genre: "Action", sizeHint: "60 GB" },
};

export function lookupKnownGame(title: string): KnownGameEntry | null {
  const lower = title.toLowerCase();
  const keys = Object.keys(KNOWN_GAMES).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    if (lower.includes(key)) return KNOWN_GAMES[key];
  }
  return null;
}
